FROM ubuntu:hirsute

RUN apt-get update \
  && apt-get install --yes \
    e2fsprogs \
    dosfstools \
    xxd \
    parted \
    udev \
    wget \
    curl \
    qemu-user-static \
    binfmt-support \
    zerofree \
    fdisk
