on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build armhf/aarch64
      uses: actions/checkout@v1
      run: |
        docker build runner -t runner
        docker run --privileged --rm -v /dev:/dev:ro -v "$PWD":/runner -w /runner -e ALPINE_BRANCH=latest-stable -e ALPINE_MIRROR="http://dl-cdn.alpinelinux.org/alpine" -e ARCH=aarch64 runner ./make-image
        docker run --privileged --rm -v /dev:/dev:ro -v "$PWD":/runner -w /runner -e ALPINE_BRANCH=latest-stable -e ALPINE_MIRROR="http://dl-cdn.alpinelinux.org/alpine" -e ARCH=armhf runner ./make-image

    - name: create release
      uses: elgohr/Github-Hub-Action@master
#      with:
#        args: release create $(date +%Y%m%d%H%M%S)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo snap install hub --classic
        build_date=$(date +%Y%m%d)
        build_number=$[$(git tag | grep $build_date | wc -l) + 1]
        tag="$build_date.$build_number"
        hub release create $tag -m "$tag" $(find . -name '*.gz' -exec echo -n '-a {} ' \;)
